langflowide:
  nameOverride: langflow
  ingress:
    enabled: false
    className: ingress-nginx-public
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: "173.32.120.109/32"
    hosts:
      - host: langflow.sandbox.nebed.io
        paths:
        - pathType: ImplementationSpecific
          path: /
  langflow:
    backend:
      replicaCount: 1
      resources:
        requests:
          cpu: 0.1
          memory: 1Gi
      image:
        repository: langflowai/langflow
        imagePullPolicy: IfNotPresent
        tag: 1.6.5
    frontend:
      resources:
        requests:
          cpu: 0.1
          memory: 200Mi
    sqlite:
      enabled: true
      volume:
        size: "1Gi"
        existingStorageClassName: "standard"