langflowide:
  nameOverride: langflow
  ingress:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: langflow.sandbox.nebed.io
        paths:
        - pathType: ImplementationSpecific
          path: /
  langflow:
    backend:
      replicaCount: 1
      resources:
        requests:
          cpu: 0.1
          memory: 1Gi
      image:
        repository: langflowai/langflow
        imagePullPolicy: IfNotPresent
        tag: 1.6.5
      persistentVolume:
        claimName: langflow-backend-pvc
        size: "50Gi"
        existingStorageClassName: "standard"
      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: langflow-backend-pvc
      volumeMounts:
        - name: backend-data
          mountPath: /app/flows
          subPath: flows
          readOnly: false
        - name: backend-data
          mountPath: /tmp
          subPath: tmp
          readOnly: false
        - name: backend-data
          mountPath: /app/data
          subPath: data
          readOnly: false
        - name: backend-data
          mountPath: /app/db
          subPath: db
          readOnly: false
    frontend:
      resources:
        requests:
          cpu: 0.1
          memory: 200Mi
    sqlite:
      enabled: true
      volume:
        size: "1Gi"
        existingStorageClassName: "standard"